### ISSUE TITLE
what is the offset vae Actual effect ？ 

### ISSUE THREAD

**Issue by DexiangHong** [lllyasviel/LayerDiffuse_DiffusersCLI#3]
I run demo_sdxl_vae_encoder_decode.py, and find there are no difference between the reconstruction results  with offset and  without offset . 

Here is the original image:
![causal_cut](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/2d511be8-e5a0-48da-8a85-3cc67d137fc2)
Here is the reconstruction with offset:
![vae_0_transparent](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/4b80a86b-328c-4caa-868a-ffbd24162739)
Here is the reconstruction without offset:
![vae_0_transparent_no_offset](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/4ef1423a-0e14-45d9-9a0b-6d140efb5e96)

Another Example:
Here is the original image:
![cat](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/977b584f-b378-4c1b-bc38-535602ba17ab)
Here is the reconstruction with offset:
![vae_0_transparent](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/ee983483-3158-4a08-85ba-04d026db4776)
Here is the reconstruction without offset:
![vae_0_transparent_no_offset](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/32900278/0f0f5f53-ced5-4bea-8e67-70c158f27b69)

**Comment by lllyasviel** [comment]
u can see some differences around semi-transparent patterns if put them on a black bg like 
![b](https://github.com/lllyasviel/LayerDiffuse_DiffusersCLI/assets/19834515/bdebb4ec-926b-4898-948a-6d5d876b1367)
using some other example with larger semi-transparent area may lead to bigger differences

the released decoder is trained with data augmentations so that it works regardless of whether the unet's diffusion provides the expected distrubution or not. This can be useful when using special checkpoints like some anime models that struggles to yield latents with accurate offsets. but using offset is recommended and has lower loss in val/test set

i can put another decoder without augmentation if demanded so that the difference will be larger, but i prefer the current one, since that another decoder without augmentation has higher failure rate when changing different base models like anime and pony etc (since those special models do not always diffuse with matched offset distrubution)
